language: c
before_install:
  - sudo apt-get update -qq
  - cd allegro-install
  - bash install.sh -qq
  - cd ..
  - cd make
install:
script:
  - make
after_script:
  - cd ..
  - cd bin
  - ./logikid --init-only